In [1]:
import torch #基本モジュール
from torch.autograd import Variable #自動微分用
import torch.nn as nn #ネットワーク構築用
import torch.optim as optim #最適化関数
import torch.nn.functional as F #ネットワーク用の様々な関数
import torch.utils.data #データセット読み込み関連
import torchvision #画像関連
from torchvision import datasets, models, transforms #画像用データセット諸々

import numpy as np
import argparse

In [9]:
inps = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
tgts = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
dataset = torch.utils.data.TensorDataset(inps, tgts)
dataset[1]

(tensor([5., 6., 7., 8., 9.]), tensor([5., 6., 7., 8., 9.]))

In [25]:
indices = torch.arange(10)
A = indices[:5]
B = indices[5:]
set = torch.utils.data.Subset(dataset, B)
set[0]

(tensor([25., 26., 27., 28., 29.]), tensor([25., 26., 27., 28., 29.]))

In [33]:
loader = torch.utils.data.DataLoader(set, batch_size=2,
                                          shuffle=False, num_workers=2)
loader

In [34]:
for d in loader:
    print(d)

[tensor([[25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.]]), tensor([[25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.]])]
[tensor([[35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.]]), tensor([[35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.]])]
[tensor([[45., 46., 47., 48., 49.]]), tensor([[45., 46., 47., 48., 49.]])]


In [84]:
N = 5
indices = np.arange(2 * N)
A = indices[:N]
B = indices[N:]
for epoch in range(30):
    print("A", A)
    print("B", B)
    
    A_loader = torch.utils.data.DataLoader(
        torch.utils.data.Subset(dataset, A), batch_size=2)
    B_loader = torch.utils.data.DataLoader(
        torch.utils.data.Subset(dataset, B), batch_size=2)
    testA = np.array([True, False, False, True, True])
    testB = np.array([True, True, False, False, True])
    
    A_o, A_x = A[testA], A[np.logical_not(testA)]
    B_o, B_x = B[testB], B[np.logical_not(testB)]
    s = min(len(A_x), len(B_o))
    A = np.concatenate([A_o, B_o[:s], A_x[s:]])
    B = np.concatenate([B_x, A_x[:s], B_o[s:]])

A [0 1 2 3 4]
B [5 6 7 8 9]
A [0 3 4 5 6]
B [7 8 1 2 9]
A [0 5 6 7 8]
B [1 2 3 4 9]
A [0 7 8 1 2]
B [3 4 5 6 9]
A [0 1 2 3 4]
B [5 6 7 8 9]
A [0 3 4 5 6]
B [7 8 1 2 9]
A [0 5 6 7 8]
B [1 2 3 4 9]
A [0 7 8 1 2]
B [3 4 5 6 9]
A [0 1 2 3 4]
B [5 6 7 8 9]
A [0 3 4 5 6]
B [7 8 1 2 9]
A [0 5 6 7 8]
B [1 2 3 4 9]
A [0 7 8 1 2]
B [3 4 5 6 9]
A [0 1 2 3 4]
B [5 6 7 8 9]
A [0 3 4 5 6]
B [7 8 1 2 9]
A [0 5 6 7 8]
B [1 2 3 4 9]
A [0 7 8 1 2]
B [3 4 5 6 9]
A [0 1 2 3 4]
B [5 6 7 8 9]
A [0 3 4 5 6]
B [7 8 1 2 9]
A [0 5 6 7 8]
B [1 2 3 4 9]
A [0 7 8 1 2]
B [3 4 5 6 9]
A [0 1 2 3 4]
B [5 6 7 8 9]
A [0 3 4 5 6]
B [7 8 1 2 9]
A [0 5 6 7 8]
B [1 2 3 4 9]
A [0 7 8 1 2]
B [3 4 5 6 9]
A [0 1 2 3 4]
B [5 6 7 8 9]
A [0 3 4 5 6]
B [7 8 1 2 9]
A [0 5 6 7 8]
B [1 2 3 4 9]
A [0 7 8 1 2]
B [3 4 5 6 9]
A [0 1 2 3 4]
B [5 6 7 8 9]
A [0 3 4 5 6]
B [7 8 1 2 9]


In [73]:
[1, 3] + [2, 2]

[1, 3, 2, 2]

In [80]:
np.concatenate([A[:2], A[-2:]])

array([0, 1, 3, 4])

In [86]:
def A(d):
    d["p"] = 1

d = {"p" : 2}
A(d)
print(d)

{'p': 1}


[1]