In [6]:
import numpy as np

In [2]:
import torch #基本モジュール
from torch.autograd import Variable #自動微分用
import torch.nn as nn #ネットワーク構築用
import torch.optim as optim #最適化関数
import torch.nn.functional as F #ネットワーク用の様々な関数
import torch.utils.data #データセット読み込み関連
import torchvision #画像関連
from torchvision import datasets, models, transforms #画像用データセット諸々

In [4]:
x = torch.Tensor(5, 3) #5x3のTensorの定義
y = torch.rand(5, 3) #5x3の乱数で初期化したTensorの定義
z = x + y #普通に演算も可能
z

tensor([[0.6734, 0.7255, 0.8297],
        [0.6392, 0.6711, 0.0583],
        [0.4717, 0.7514, 0.7161],
        [0.1316, 0.7292, 0.0428],
        [0.3596, 0.7041, 0.1677]])

In [7]:
x = np.random.rand(5, 3)
y = torch.from_numpy(x)
z = y.numpy()
z

array([[0.42342585, 0.33555479, 0.29075874],
       [0.36765733, 0.34344352, 0.78701321],
       [0.30387349, 0.78670604, 0.34113698],
       [0.63137639, 0.15118779, 0.57048147],
       [0.93061811, 0.09039157, 0.85976858]])

In [9]:
x = torch.rand(5, 3)
y = Variable(x)
z = torch.pow(y,2) + 2 #y_i**2 + 2
z

tensor([[2.3733, 2.0198, 2.3989],
        [2.0134, 2.0275, 2.2160],
        [2.3059, 2.0322, 2.0132],
        [2.2912, 2.8298, 2.0023],
        [2.1773, 2.6367, 2.0049]])

In [12]:
#画像の変形処理
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

#CIFAR-10のTensorに変形前のtrainsetのロード
rawtrainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True)

#CIFAR-10のtrain, testsetのロード
#変形はtransformを適用
trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)

#DataLoaderの適用->これによりバッチの割り当て・シャッフルをまとめて行うことができる
#batch_sizeでバッチサイズを指定
#num_workersでいくつのコアでデータをロードするか指定(デフォルトはメインのみ)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
