# Define

## import

In [1]:
import torch #基本モジュール
from torch.autograd import Variable #自動微分用
import torch.nn as nn #ネットワーク構築用
import torch.optim as optim #最適化関数
import torch.nn.functional as F #ネットワーク用の様々な関数
import torch.utils.data #データセット読み込み関連
import torchvision #画像関連
from torch import Tensor
from torchvision import datasets, models, transforms #画像用データセット諸々

import numpy as np
import argparse
import json
from logging.config import dictConfig
from logging import getLogger
import os
import time
from google.colab import files
import itertools

## Components

In [2]:
class Zero(nn.Module):
  def __init__(self, stride):
    super(Zero, self).__init__()
    self.stride = stride

  def forward(self, x):
    if self.stride == 1:
      return x.mul(0.)
    return x[:,:,::self.stride,::self.stride].mul(0.)

In [3]:
class FactorizedReduce(nn.Module):
  def __init__(self, C_in, C_out, affine=True):
    super(FactorizedReduce, self).__init__()
    assert C_out % 2 == 0
    self.relu = nn.ReLU(inplace=False)
    self.conv_1 = nn.Conv2d(C_in, C_out // 2, 1, stride=2, padding=0, bias=False)
    self.conv_2 = nn.Conv2d(C_in, C_out // 2, 1, stride=2, padding=0, bias=False) 
    self.bn = nn.BatchNorm2d(C_out, affine=affine)

  def forward(self, x):
    x = self.relu(x)
    # strideの偶奇による情報ロスを防ぐ
    out = torch.cat([self.conv_1(x), self.conv_2(x[:,:,1:,1:])], dim=1)
    out = self.bn(out)
    return out

In [4]:
class ReLUConvBN(nn.Module):

  def __init__(self, C_in, C_out, kernel_size, stride, padding, affine=True):
    super(ReLUConvBN, self).__init__()
    self.op = nn.Sequential(
      nn.ReLU(inplace=False),
      nn.Conv2d(C_in, C_out, kernel_size, stride=stride, padding=padding, bias=False),
      nn.BatchNorm2d(C_out, affine=affine)
    )

  def forward(self, x):
    return self.op(x)

In [5]:
class DilConv(nn.Module):
    
  def __init__(self, C_in, C_out, kernel_size, stride, padding, dilation, affine=True):
    super(DilConv, self).__init__()
    self.op = nn.Sequential(
      nn.ReLU(inplace=False),
      nn.Conv2d(C_in, C_in, kernel_size=kernel_size, stride=stride, padding=padding, dilation=dilation, groups=C_in, bias=False),
      nn.Conv2d(C_in, C_out, kernel_size=1, padding=0, bias=False),
      nn.BatchNorm2d(C_out, affine=affine),
      )

  def forward(self, x):
    return self.op(x)

In [6]:
class SepConv(nn.Module):
    
  def __init__(self, C_in, C_out, kernel_size, stride, padding, affine=True):
    super(SepConv, self).__init__()
    self.op = nn.Sequential(
      nn.ReLU(inplace=False),
      nn.Conv2d(C_in, C_in, kernel_size=kernel_size, stride=stride, padding=padding, groups=C_in, bias=False),
      nn.Conv2d(C_in, C_in, kernel_size=1, padding=0, bias=False),
      nn.BatchNorm2d(C_in, affine=affine),
      nn.ReLU(inplace=False),
      nn.Conv2d(C_in, C_in, kernel_size=kernel_size, stride=1, padding=padding, groups=C_in, bias=False),
      nn.Conv2d(C_in, C_out, kernel_size=1, padding=0, bias=False),
      nn.BatchNorm2d(C_out, affine=affine),
      )

  def forward(self, x):
    return self.op(x)

In [7]:
class Edge(nn.Module):
  def __init__(self, operators, theta=None):
    super(Edge, self).__init__()
    self.operators = operators

  def forward(self, input: Tensor, theta: Tensor) -> Tensor:
    return sum(t * op(input) for t, op in zip(theta, self.operators))

In [8]:
class Graph():
  def __init__(self, node_num : int, input : int=1, output : int=1):
    self.node_num = node_num
    self.input = input
    self.output = output
    self.middle = node_num - input - output
    self._graph = self._make_graph(node_num)
    self._order = self._ordered_edges(1)
  
  def edges(self):
    return self._graph

  def _ordered_edges(self, agg : int):
    g = self._graph
    r = [i for i in range(self.node_num)][self.input:-self.output]
    return [[idx for idx, t in enumerate(g) if t[agg] == i] for i in r]

  # edge indices to each intermediate node
  def ordered_edges(self):
    return self._order

  def size(self):
    return len(self._graph)

  def _make_graph(self, num : int):
    l = [i for i in range(num - self.output)]
    return [(s, e) for (s, e) in itertools.combinations(l, 2) if e >= self.input]

In [9]:
import sys
from graphviz import Digraph

def plot(graph, theta, multi, filename):
  g = Digraph(
      format='png', #pdf
      edge_attr=dict(fontsize='20', fontname="times"),
      node_attr=dict(style='filled', shape='rect', align='center', fontsize='20', height='0.5', width='0.5', penwidth='2', fontname="times"),
      engine='dot')
  g.body.extend(['rankdir=LR'])

  for i in range(graph.node_num):
    color = 'lightblue'
    color = 'darkseagreen2' if graph.input > i else color
    color = 'palegoldenrod' if graph.node_num - graph.output <= i else color
    g.node(str(i), fillcolor=color)
  
  for idx, (s, e) in enumerate(graph.edges()):
    op = [CANDIDATE[i] for i, p in enumerate(theta[idx]) if p >= 1.0]
    if len(op) == 0: continue
    g.edge(str(s), str(e), label=op[0], fillcolor="gray")

  for i in range(graph.node_num - 1 - multi, graph.node_num - 1):
    g.edge(str(i), str(graph.node_num - graph.output), fillcolor="gray")

  g.render(filename, view=True)
  return g

## Operator

In [10]:
OPS = {
  'none' : lambda C, stride, affine: Zero(stride),
  'skip_connect' : lambda C, stride, affine: nn.Identity() if stride == 1 else FactorizedReduce(C, C, affine=affine),
  'avg_pool_3x3' : lambda C, stride, affine: nn.Sequential(nn.AvgPool2d(3, stride=stride, padding=1, count_include_pad=False), nn.BatchNorm2d(C, affine=False)),
  'max_pool_3x3' : lambda C, stride, affine: nn.Sequential(nn.MaxPool2d(3, stride=stride, padding=1), nn.BatchNorm2d(C, affine=False)),
  'conv_3x3' : lambda C, stride, affine: nn.Conv2d(C, C, 3, stride=stride, padding=1),
  'conv_5x5' : lambda C, stride, affine: nn.Conv2d(C, C, 5, stride=stride, padding=2),
  'ReLUConvBN' : lambda C, stride, affine: ReLUConvBN(C, C, 3, stride=stride, padding=1),
  'sep_conv_3x3' : lambda C, stride, affine: SepConv(C, C, 3, stride, 1, affine=affine),
  'sep_conv_5x5' : lambda C, stride, affine: SepConv(C, C, 5, stride, 2, affine=affine),
  'sep_conv_7x7' : lambda C, stride, affine: SepConv(C, C, 7, stride, 3, affine=affine),
  'dil_conv_3x3' : lambda C, stride, affine: DilConv(C, C, 3, stride, 2, 2, affine=affine),
  'dil_conv_5x5' : lambda C, stride, affine: DilConv(C, C, 5, stride, 4, 2, affine=affine),
  'conv_7x1_1x7' : lambda C, stride, affine: nn.Sequential(
    nn.ReLU(inplace=False),
    nn.Conv2d(C, C, (1,7), stride=(1, stride), padding=(0, 3), bias=False),
    nn.Conv2d(C, C, (7,1), stride=(stride, 1), padding=(3, 0), bias=False),
    nn.BatchNorm2d(C, affine=affine)
    ),
}

In [11]:
CANDIDATE = [
  'conv_3x3',
  'conv_5x5',
  # 'ReLUConvBN',
  'avg_pool_3x3',
  'max_pool_3x3',
  'skip_connect',
  'none',
]
CANDIDATE = [
  'none',
  'skip_connect',
  # 'avg_pool_3x3',
  'max_pool_3x3',
  'sep_conv_3x3',
  'sep_conv_5x5',
  # 'sep_conv_7x7',
  'dil_conv_3x3',
  'dil_conv_5x5',
  # 'conv_7x1_1x7',
]

## module

In [12]:
from typing import List
class Cell(nn.Module):
  def __init__(self, names, graph, cs, multi, reduces=[False], search=True):
    super(Cell, self).__init__()
    assert len(cs) == len(reduces) + 1
    c = cs[-1]
    self.reduce = reduces[-1]
    self.pres = nn.ModuleList([
      FactorizedReduce(c_prev, c, affine=False) if reduce else
      ReLUConvBN(c_prev, c, 1, 1, 0, affine=False)
      for c_prev, reduce in zip(cs[:-1], reduces[:-1] + [False])
    ])

    self.search = search
    self.graph = graph
    self.multi = multi
    self.edges = nn.ModuleList(
      [Edge(self._mix_operators(names, c, r)) for r in self.graph.edges()]
    )

  def _mix_operators(self, names, c, r):
    modules = []
    stride = 2 if self.reduce and r[0] < self.graph.input else 1
    affine = not self.search
    for name in names:
      modules += [OPS[name](c, stride, affine)]
    return nn.ModuleList(modules)

  def forward(self, inputs: List[Tensor], theta: Tensor) -> Tensor:
    nodes = [p(i) for p, i in zip(self.pres, inputs)]

    refs = self.graph.edges()
    for idc in self.graph.ordered_edges():
      output = sum(self.edges[idx](nodes[refs[idx][0]], theta[idx]) for idx in idc)
      nodes += [output]
    
    return torch.cat(nodes[-self.multi:], dim=1)

In [13]:

# TODO : check point (epoch)
# TODO : show layer shape
# TODO : replace to networkx
class CellNetwork(nn.Module):
  def __init__(self, depth = 4, node_num = 4, input = 1, init_channel = 16, class_num = 10, multi = -1, search = True):
    super(CellNetwork, self).__init__()
    self.depth = depth
    self.search = search
    self.onehot = False
    self.graph = Graph(node_num, input)
    self.multi = self.graph.middle if multi <= 0 else multi
    self.init_modules(3, self.multi, class_num, init_channel)
    self.init_theta()
    
    print(self.graph.edges())
    print(CANDIDATE)

  def is_reduce(self, idx):
    return self.depth//3 == idx or 2*self.depth//3 == idx

  def init_theta(self, zero=True, delta=1e-3):
    if zero:
      normal_theta = torch.zeros(self.graph.size(), len(CANDIDATE), requires_grad=True)
      reduce_theta = torch.zeros(self.graph.size(), len(CANDIDATE), requires_grad=True)
    else:
      normal_theta = delta * torch.randn(self.graph.size(), len(CANDIDATE), requires_grad=True)
      reduce_theta = delta * torch.randn(self.graph.size(), len(CANDIDATE), requires_grad=True)
    self.thetas = [normal_theta, reduce_theta]

  def init_modules(self, c, multi, class_num, ini_c):
    # stem
    # c_n = c * multi
    c_n = ini_c
    self.stem = nn.Sequential(
      nn.Conv2d(c, c_n, 3, padding=1, bias=False),
      nn.BatchNorm2d(c_n)
    )
    c = ini_c

    # cells
    input = self.graph.input
    reduces = [False for _ in range(input)]
    cs = [c_n for _ in range(input)]
    self.cells = nn.ModuleList()
    for i in range(self.depth):
      reduces += [self.is_reduce(i)]
      if self.is_reduce(i):
        c *= 2
      
      cell = Cell(CANDIDATE, self.graph, cs[-input:] + [c], multi, reduces=reduces[-input:], search=self.search)
      self.cells += [cell]
      cs += [multi * c]
    
    # classify
    self.pooling = nn.AdaptiveAvgPool2d(1)
    self.linear = nn.Linear(cs[-1], class_num)

  def forward(self, input) -> Tensor:
    s = self.stem(input)
    input_num = self.graph.input
    stas = [s] * input_num

    for idx, cell in enumerate(self.cells):
      theta = self.thetas[1] if cell.reduce else self.thetas[0]
      weights = theta if self.onehot else F.softmax(theta, dim=-1)
      s = cell(stas[-input_num:], weights)
      stas += [s]

    out = self.pooling(s)
    return self.linear(out.view(out.size(0), -1))
  
  def to(self, *args, **kwargs):
    with torch.no_grad():
      for idx, theta in enumerate(self.thetas):
        self.thetas[idx] = theta.to(*args, **kwargs)

    return super(CellNetwork, self).to(*args, **kwargs)

  def learn_theta(self, is_learn: bool):
    for theta in self.thetas:
      theta.requires_grad = is_learn

  def sampling(self, inplace=True):
    def _sampling(theta, degree=2, graph=self.graph, ignore=CANDIDATE.index('none')):
      with torch.no_grad():
        for t in theta:
          t[ignore] = t.min(0).values
          max = t.max(0)
          t[:] = 0.0
          t[max.indices] = max.values

        for edges in graph.ordered_edges():
          values = [(e, theta[e].argmax(), theta[e].max(0).values) for e in edges]
          select = min(len(values), degree)
          edges = sorted(values, key=lambda x: -x[2])[:select]
          
          for (e, o, v) in values:
            theta[e][o] = 0.0
          for (e, o, v) in edges:
            theta[e][o] = 1.0
            
    if inplace:
      for theta in self.thetas:
        _sampling(theta)
        
      self.learn_theta(False)
      self.onehot = True
    else:
      thetas = [theta.detach().clone() for theta in self.thetas]
      for theta in thetas:
        _sampling(theta)
      return thetas
  
  def plot(self, prefix):
    thetas = self.sampling(inplace=False)
    return [plot(self.graph, theta, self.multi, prefix + name)
      for theta, name in zip(thetas, ["normal", "reduce"])]

  def log(self):
    print("Network")
    for theta in self.thetas:
      print(F.softmax(theta, dim=-1))

# Unit Test

In [14]:
import unittest

def tensor_equal(x, y):
  return (torch.sum(x == y) == x.view(-1).shape[0]).item()

class TestEdge(unittest.TestCase):
  def test_id(self):
    input = torch.randn(1, 3, 32, 32)
    operators = [nn.Identity(), None]
    model = Edge(operators, theta=torch.tensor([1.0, 0.0]))
    output = model(input)
    self.assertEqual(tensor_equal(input, output), True)

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

E
ERROR: test_id (__main__.TestEdge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-14-7c4fb3f2b357>", line 11, in test_id
    output = model(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'theta'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)


# Training

## training

In [15]:
from tqdm.notebook import tqdm
def train(model, device, train_loader, valid_loader, optimizer, optimizerB, criterion, logger, class_array):
    model.train()
    class_array = torch.LongTensor(class_array).to(device)
    for batch_idx, (data, target) in enumerate(tqdm(train_loader)):
        data, target = data.to(device), target.to(device)

        if optimizerB:
          data_v, target_v = next(iter(valid_loader))
          data_v, target_v = data_v.to(device), target_v.to(device)

          # # theta update
          optimizerB.zero_grad()
          output = model(data_v)
          reg = torch.zeros(output.shape[0], 10).to(device)
          reg.index_add_(1, class_array, output)
          loss = criterion(reg, target_v)
          loss.backward()
          optimizerB.step()

        optimizer.zero_grad()
        output = model(data)
        reg = torch.zeros(output.shape[0], 10).to(device)
        reg.index_add_(1, class_array, output)
        loss = criterion(reg, target)
        loss.backward(retain_graph=True)
        # clip
        optimizer.step()
        
    return (None, loss.item())

In [16]:
def test(model, device, test_loader, criterion, logger, class_array):
    model.eval()
    test_loss = []
    correct = 0
    class_array = torch.tensor(class_array).to(device)
    with torch.no_grad():
        for batch_idx, (data, target) in enumerate(test_loader):
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss.append(criterion(output, target).item())
            pred = class_array[output.argmax(dim=1, keepdim=True)]
            correct += pred.eq(target.view_as(pred)).sum().item()
            
    test_loss = np.mean(np.array(test_loss))
    accuracy = 100. * correct / len(test_loader.dataset)
    
    return (None, (test_loss, accuracy))

## Utils

In [17]:
from argparse import Namespace
def dictspace(f):
  def inner(**kwds):
    return f(Namespace(**kwds))
  return inner

In [18]:
class Store():
  def __init__(self, dir="result", name="log"):
    self.dict = {}
    self.dir = dir
  
  def add(self, name, value):
    if not name in self.dict:
      self.dict[name] = []
    self.dict[name].append(value)
  
  def save(self, name="log"):
    path = os.path.join(self.dir, name + ".txt")
    with open(path, mode='w') as f:
      f.write("%s" % self.dict)

  def save_fig(self, metrix="acc", xlabel="epochs", ylabel="accuracy[%]"):
    import matplotlib.pyplot as plt
    
    times = len(self.dict[metrix])
    fig = plt.figure()
    plt.plot(np.arange(times), self.dict[metrix])
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend()
    plt.show()
    fig.savefig(os.path.join(self.dir, "%s_%d.png" % (metrix, times)))

  def __repr__(self):
    return "store in %s" % self.dict

In [19]:
def SaveModel(name, model, dir="result"):
  path = os.path.join(dir, name + ".pt")
  if not os.path.exists(dir):
    os.mkdir(dir)

  torch.save(model.state_dict(), path)
  # print(os.path.join("/content", result_path))
  # files.download(os.path.join("/content", result_path))

In [20]:
def load_dataset(train=2000, test=500, valid=0):
  #画像の変形処理
  transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
  ])

  transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
  ])

  #CIFAR-10のtrain, testsetのロード
  trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                          download=True, transform=transform)
  testset = torchvision.datasets.CIFAR10(root='./data', train=False, 
                                          download=True, transform=transform_test)
  
  trainset, validset, _ = torch.utils.data.random_split(trainset, [train, valid, 50000-train-valid])
  testset, _ = torch.utils.data.random_split(testset, [test, 10000-test])
  return trainset, testset, validset

In [21]:
class EarlyStopping:
  def __init__(self, dir="min", patent=5):
    self.list = []
    self.best = 0
    self.patent = patent
    self.count = 0
    self.order = dir == "max"

  def step(self, item):
    def _score(item):
      return item * (1 if self.order else -1)

    if len(self.list) == 0:
      self.best = _score(item)

    self.list.append(item)
    item = _score(item)
    if self.best < item:
      self.best = item
      self.count = 0
    else:
      self.count += 1

  def is_stop(self):
    return self.patent <= self.count

In [22]:
def setup_drive():
  # Install a Drive FUSE wrapper.
  # https://github.com/astrada/google-drive-ocamlfuse
  !apt-get install -y -qq software-properties-common python-software-properties module-init-tools
  !add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
  !apt-get update -qq 2>&1 > /dev/null
  !apt-get -y install -qq google-drive-ocamlfuse fuse

  # Generate auth tokens for Colab
  from google.colab import auth
  auth.authenticate_user()

  # Generate creds for the Drive FUSE library.
  from oauth2client.client import GoogleCredentials
  creds = GoogleCredentials.get_application_default()
  import getpass
  !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
  vcode = getpass.getpass()
  !echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

In [23]:
def save_dir(dir : str, drivepath = './drive/My Drive/ml'):
  if not "getpass" in sys.modules:
    setup_drive()

  if dir:
    import subprocess
    res = subprocess.run(["cp", "-r", "./" + dir, drivepath], stdout=subprocess.PIPE)
    sys.stdout.write(res.stdout)

In [24]:
def get_time():
  import datetime
  import pytz
  dt_now = datetime.datetime.now(pytz.timezone('Asia/Tokyo'))
  return dt_now.strftime('%Y_%m_%d %H_%M %S')

In [25]:
def save_heatmap(data, path):
  import seaborn as sns
  import matplotlib.pyplot as plt
  
  plt.figure()
  sns.heatmap(data, annot=True, fmt="1.2f")
  plt.savefig(path)
  plt.close('all')

## main

In [26]:
def main(description, **kwarg):

  save_dir("")

  use_cuda = torch.cuda.is_available()
  device = torch.device("cuda" if use_cuda else "cpu")
  print("device is %s" % device)

  # trainset, testset = load_dataset()
  kwargs = {'num_workers': 2, 'pin_memory': True} if use_cuda else {}

  class_array = [i for i in range(10)]

  @dictspace
  def learning(args):

    store = Store(dir=args.dir)
    store.add("kwargs", args)
    theta_log = Store(dir=args.dir)

    # instantiate
    networkarg = {"depth" : args.depth, "node_num" : args.node,
                  "input" : args.input, "multi" : args.multi}
    model = CellNetwork(**networkarg)
    model.to(device)

    optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum, weight_decay=3e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, float(args.epochs), eta_min=0.001)
    optimizer_theta = optim.Adam(model.thetas, lr=args.lr_theta, betas=(0.5, 0.999), weight_decay=1e-3)
    criterion = nn.CrossEntropyLoss()

    trainset, testset, validset = load_dataset(train=args.train_size, valid=args.train_size)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=args.batch_size, **kwargs)
    validloader = torch.utils.data.DataLoader(validset, batch_size=args.batch_size, **kwargs)
    testloader = torch.utils.data.DataLoader(testset, batch_size=args.batch_size, **kwargs)
    
    # architecture search
    time_sta = time.time()
    accuracy, loss = 0, 1e10
    model.learn_theta(False)
    !nvidia-smi
    for epoch in range(args.epochs):
      
      if epoch == args.switch:
        model.learn_theta(True)
        
      model.log()

      (_, loss_train) = train(model, device, trainloader, validloader, optimizer, optimizer_theta, criterion, None, class_array)
      (_, (loss_test, acc)) = test(model, device, testloader, criterion, None, class_array)
      scheduler.step()

      print('epoch %d, acc %s' % (epoch, acc))
      if epoch >= args.switch and epoch % 5 == 0:
        model.plot(os.path.join(args.dir, "epoch%d_" % epoch))
        if args.save_dir: save_dir(args.dir)
      store.add("loss", loss_test)
      store.add("acc", acc)
      theta_log.add("theta_n", model.thetas[0].detach().cpu().clone().numpy())
      theta_log.add("theta_r", model.thetas[1].detach().cpu().clone().numpy())
      save_heatmap(model.thetas[0].detach().cpu().clone().numpy(), os.path.join(args.dir, "theta_%s.png" % epoch))

      accuracy, loss = acc, loss_test
      if time.time() - time_sta >= 60 * args.minutes:
        break 

    print("\naccuracy ", accuracy, end=", ")
    print("loss ", loss)
    model.plot(os.path.join(args.dir, "complete_"))
    SaveModel("cell", model, dir=args.dir)

    # relearning
    stop = EarlyStopping(patent=15)
    accuracy, loss = 0, 1e10
    remodel = CellNetwork(search=False, **networkarg).to(device)
    remodel.thetas = model.sampling(inplace=False)
    remodel.sampling()
    model.cpu()
    del model
    model = remodel

    trainset, testset, _ = load_dataset(train=args.train_size * 2)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=args.batch_size, **kwargs)
    testloader = torch.utils.data.DataLoader(testset, batch_size=args.batch_size, **kwargs)
    
    optimizer = optim.SGD(model.parameters(), lr=args.relr, momentum=args.momentum, weight_decay=3e-4)
    # scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, float(args.epochs), eta_min=0.001)
    for epoch in range(args.epochs):
      
      (_, loss_train) = train(model, device, trainloader, None, optimizer, None, criterion, None, class_array)
      (_, (loss_test, acc)) = test(model, device, testloader, criterion, None, class_array)
      # scheduler.step()

      print('epoch %d, acc %s' % (epoch, acc))
      store.add("loss", loss_test)
      store.add("acc", acc)
      store.save()
      store.save_fig()

      accuracy, loss = acc, loss_test
      stop.step(loss_test)
      if stop.is_stop():
        break

    print("\naccuracy ", accuracy, end=", ")
    print("loss ", loss)
    SaveModel("cell", model, dir=args.dir)
    print(store)
    store.save()
    theta_log.save(name="theta")
    store.save_fig()
    if args.save_dir: save_dir(args.dir)

    model.cpu()
    del model

    return loss

  kwarg['dir'] = get_time()
  if not os.path.exists(kwarg['dir']):
    os.mkdir(kwarg['dir'])
  learning(**kwarg)

In [27]:
!cat /proc/uptime | awk '{print $1 /60 /60 /24 "days (" $1 "sec)"}'

0.150178days (12975.42sec)


In [ ]:
if __name__ == '__main__':
  # # paper
  # main("", lr=0.0250, lr_theta=0.0003, relr=0.0010, batch_size=64, train_size=20000, momentum=0.9, 
  #          epochs=50, switch=0, minutes=180, depth=8, node=7, multi=4, input=2, save_dir=True)

  # main("", lr=0.0100, lr_theta=0.0002, batch_size=64, train_size=20000, momentum=0.9, 
  #          epochs=90, switch=30, minutes=180, depth=5, node=7, multi=2)
  # main("", lr=0.0100, lr_theta=0.0002, batch_size=64, train_size=20000, momentum=0.9, 
  #          epochs=90, switch=10, minutes=180, depth=5, node=7, multi=2)
  # main("", lr=0.0050, lr_theta=0.0005, batch_size=64, train_size=4000, momentum=0.9, 
  #          epochs=15, switch=5, minutes=180, depth=4, node=4, multi=2)
  # annealing cosine scheduler no restart
  # main("", lr=0.0250, lr_theta=0.0002, relr=0.0050, batch_size=64, train_size=1000, momentum=0.9, 
  #          epochs=10, switch=0, minutes=180, depth=5, node=7, multi=4, input=2, save_dir=True)
  main("", lr=0.0200, lr_theta=0.0002, relr=0.0030, batch_size=64, train_size=25000, momentum=0.9, 
           epochs=50, switch=10, minutes=180, depth=5, node=7, multi=-1, input=2, save_dir=True)

  # main("", lr=0.0100, lr_theta=0.0002, relr=0.0010, batch_size=64, train_size=20000, momentum=0.9, 
  #          epochs=50, switch=10, minutes=180, depth=5, node=7, multi=4, input=2, save_dir=True)
  # main("", lr=0.0080, lr_theta=0.0001, relr=0.0010, batch_size=64, train_size=4000, momentum=0.9, 
  #          epochs=30, switch=10, minutes=180, depth=5, node=7, multi=4, input=2, save_dir=True)
  # main("", lr=0.0080, lr_theta=0.0001, relr=0.0010, batch_size=64, train_size=400, momentum=0.9, 
  #          epochs=1, switch=0, minutes=180, depth=3, node=7, multi=4, input=2, save_dir=True)

device is cuda
[(0, 2), (0, 3), (0, 4), (0, 5), (1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)]
['none', 'skip_connect', 'max_pool_3x3', 'sep_conv_3x3', 'sep_conv_5x5', 'dil_conv_3x3', 'dil_conv_5x5']
Files already downloaded and verified
Files already downloaded and verified
Thu Sep  3 03:41:22 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0  

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 0, acc 58.2


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0')
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 1, acc 66.8
Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0')
tensor([[0.1429, 0.1429,

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 2, acc 67.8
Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0')
tensor([[0.1429, 0.1429,

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe



epoch 3, acc 72.0
Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0')
tensor([[0.1429, 0.1429,

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 4, acc 74.8
Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0')
tensor([[0.1429, 0.1429,

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 5, acc 77.6
Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0')
tensor([[0.1429, 0.1429,

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 6, acc 77.8
Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0')
tensor([[0.1429, 0.1429,

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe



epoch 7, acc 78.2
Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0')
tensor([[0.1429, 0.1429,

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 8, acc 78.4
Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0')
tensor([[0.1429, 0.1429,

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 9, acc 79.8
Network
tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429]],
       device='cuda:0', grad_fn=<SoftmaxBackward

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 10, acc 79.6
Network
tensor([[0.1357, 0.1440, 0.1459, 0.1497, 0.1407, 0.1396, 0.1443],
        [0.1393, 0.1425, 0.1460, 0.1398, 0.1447, 0.1446, 0.1431],
        [0.1506, 0.1417, 0.1423, 0.1370, 0.1439, 0.1352, 0.1493],
        [0.1373, 0.1365, 0.1382, 0.1540, 0.1517, 0.1360, 0.1463],
        [0.1491, 0.1452, 0.1504, 0.1441, 0.1408, 0.1381, 0.1323],
        [0.1447, 0.1407, 0.1469, 0.1471, 0.1402, 0.1453, 0.1351],
        [0.1503, 0.1409, 0.1463, 0.1392, 0.1370, 0.1421, 0.1441],
        [0.1405, 0.1456, 0.1509, 0.1472, 0.1366, 0.1356, 0.1436],
        [0.1480, 0.1458, 0.1460, 0.1400, 0.1432, 0.1366, 0.1403],
        [0.1474, 0.1363, 0.1417, 0.1496, 0.1430, 0.1348, 0.1473],
        [0.1428, 0.1407, 0.1441, 0.1484, 0.1346, 0.1522, 0.1373],
        [0.1499, 0.1408, 0.1428, 0.1349, 0.1456, 0.1500, 0.1360],
        [0.1505, 0.1423, 0.1425, 0.1395, 0.1335, 0.1425, 0.1493],
        [0.1447, 0.1394, 0.1418, 0.1359, 0.1497, 0.1485, 0.1399]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 11, acc 81.0
Network
tensor([[0.1305, 0.1455, 0.1482, 0.1550, 0.1369, 0.1364, 0.1476],
        [0.1375, 0.1409, 0.1483, 0.1353, 0.1463, 0.1465, 0.1451],
        [0.1593, 0.1429, 0.1438, 0.1319, 0.1404, 0.1270, 0.1546],
        [0.1320, 0.1315, 0.1389, 0.1616, 0.1565, 0.1297, 0.1498],
        [0.1538, 0.1470, 0.1566, 0.1463, 0.1408, 0.1336, 0.1219],
        [0.1476, 0.1402, 0.1524, 0.1444, 0.1362, 0.1524, 0.1268],
        [0.1584, 0.1406, 0.1516, 0.1351, 0.1295, 0.1447, 0.1400],
        [0.1398, 0.1462, 0.1596, 0.1524, 0.1316, 0.1279, 0.1425],
        [0.1512, 0.1470, 0.1497, 0.1336, 0.1478, 0.1345, 0.1363],
        [0.1485, 0.1302, 0.1395, 0.1577, 0.1426, 0.1272, 0.1543],
        [0.1432, 0.1397, 0.1479, 0.1506, 0.1285, 0.1602, 0.1299],
        [0.1567, 0.1392, 0.1398, 0.1277, 0.1468, 0.1589, 0.1309],
        [0.1571, 0.1417, 0.1425, 0.1346, 0.1265, 0.1449, 0.1527],
        [0.1488, 0.1367, 0.1427, 0.1290, 0.1543, 0.1517, 0.1366]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 12, acc 79.0
Network
tensor([[0.1288, 0.1461, 0.1489, 0.1581, 0.1328, 0.1357, 0.1496],
        [0.1367, 0.1393, 0.1501, 0.1324, 0.1499, 0.1497, 0.1419],
        [0.1675, 0.1433, 0.1451, 0.1272, 0.1348, 0.1199, 0.1622],
        [0.1291, 0.1269, 0.1375, 0.1728, 0.1576, 0.1234, 0.1527],
        [0.1556, 0.1508, 0.1647, 0.1482, 0.1381, 0.1298, 0.1129],
        [0.1474, 0.1403, 0.1557, 0.1452, 0.1360, 0.1557, 0.1197],
        [0.1625, 0.1419, 0.1586, 0.1288, 0.1246, 0.1458, 0.1378],
        [0.1385, 0.1467, 0.1665, 0.1558, 0.1295, 0.1206, 0.1424],
        [0.1561, 0.1454, 0.1483, 0.1285, 0.1510, 0.1352, 0.1354],
        [0.1531, 0.1273, 0.1391, 0.1654, 0.1359, 0.1219, 0.1573],
        [0.1459, 0.1398, 0.1506, 0.1482, 0.1218, 0.1699, 0.1238],
        [0.1647, 0.1398, 0.1368, 0.1178, 0.1427, 0.1686, 0.1295],
        [0.1679, 0.1415, 0.1400, 0.1303, 0.1201, 0.1459, 0.1543],
        [0.1536, 0.1332, 0.1419, 0.1233, 0.1562, 0.1556, 0.1362]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 13, acc 80.8
Network
tensor([[0.1258, 0.1471, 0.1512, 0.1670, 0.1267, 0.1302, 0.1520],
        [0.1322, 0.1381, 0.1549, 0.1294, 0.1552, 0.1489, 0.1414],
        [0.1710, 0.1444, 0.1475, 0.1227, 0.1327, 0.1130, 0.1687],
        [0.1243, 0.1233, 0.1376, 0.1814, 0.1595, 0.1190, 0.1550],
        [0.1603, 0.1526, 0.1739, 0.1423, 0.1366, 0.1279, 0.1063],
        [0.1531, 0.1380, 0.1582, 0.1489, 0.1326, 0.1543, 0.1150],
        [0.1679, 0.1427, 0.1639, 0.1204, 0.1228, 0.1462, 0.1361],
        [0.1369, 0.1437, 0.1734, 0.1602, 0.1281, 0.1160, 0.1417],
        [0.1605, 0.1445, 0.1482, 0.1282, 0.1501, 0.1333, 0.1351],
        [0.1566, 0.1235, 0.1372, 0.1763, 0.1295, 0.1150, 0.1617],
        [0.1481, 0.1372, 0.1503, 0.1487, 0.1171, 0.1776, 0.1210],
        [0.1700, 0.1387, 0.1348, 0.1115, 0.1450, 0.1750, 0.1251],
        [0.1778, 0.1405, 0.1405, 0.1246, 0.1141, 0.1446, 0.1580],
        [0.1556, 0.1308, 0.1451, 0.1177, 0.1600, 0.1556, 0.1353]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe



epoch 14, acc 83.0
Network
tensor([[0.1228, 0.1471, 0.1543, 0.1713, 0.1185, 0.1308, 0.1552],
        [0.1286, 0.1373, 0.1604, 0.1235, 0.1648, 0.1456, 0.1398],
        [0.1770, 0.1458, 0.1510, 0.1173, 0.1282, 0.1050, 0.1757],
        [0.1225, 0.1200, 0.1364, 0.1861, 0.1652, 0.1138, 0.1559],
        [0.1632, 0.1577, 0.1861, 0.1363, 0.1350, 0.1236, 0.0980],
        [0.1605, 0.1372, 0.1621, 0.1506, 0.1293, 0.1488, 0.1115],
        [0.1741, 0.1398, 0.1671, 0.1119, 0.1164, 0.1538, 0.1368],
        [0.1381, 0.1410, 0.1802, 0.1601, 0.1261, 0.1087, 0.1458],
        [0.1658, 0.1433, 0.1441, 0.1306, 0.1515, 0.1278, 0.1369],
        [0.1617, 0.1185, 0.1329, 0.1882, 0.1274, 0.1071, 0.1642],
        [0.1526, 0.1360, 0.1470, 0.1480, 0.1128, 0.1857, 0.1178],
        [0.1769, 0.1375, 0.1312, 0.1046, 0.1421, 0.1840, 0.1238],
        [0.1885, 0.1378, 0.1363, 0.1219, 0.1077, 0.1439, 0.1638],
        [0.1604, 0.1252, 0.1428, 0.1126, 0.1642, 0.1581, 0.1367]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 15, acc 78.8
Network
tensor([[0.1161, 0.1494, 0.1562, 0.1760, 0.1120, 0.1318, 0.1585],
        [0.1242, 0.1412, 0.1693, 0.1195, 0.1734, 0.1384, 0.1340],
        [0.1801, 0.1461, 0.1535, 0.1141, 0.1232, 0.0992, 0.1837],
        [0.1210, 0.1153, 0.1335, 0.1907, 0.1700, 0.1113, 0.1583],
        [0.1735, 0.1559, 0.1917, 0.1318, 0.1358, 0.1190, 0.0924],
        [0.1705, 0.1328, 0.1631, 0.1538, 0.1256, 0.1431, 0.1111],
        [0.1774, 0.1321, 0.1671, 0.1068, 0.1149, 0.1609, 0.1409],
        [0.1380, 0.1346, 0.1801, 0.1648, 0.1247, 0.1043, 0.1535],
        [0.1704, 0.1438, 0.1432, 0.1301, 0.1517, 0.1258, 0.1350],
        [0.1644, 0.1149, 0.1314, 0.1997, 0.1215, 0.1014, 0.1666],
        [0.1578, 0.1338, 0.1437, 0.1496, 0.1091, 0.1936, 0.1125],
        [0.1861, 0.1366, 0.1283, 0.0963, 0.1430, 0.1882, 0.1216],
        [0.2026, 0.1363, 0.1352, 0.1174, 0.1028, 0.1416, 0.1642],
        [0.1637, 0.1204, 0.1404, 0.1091, 0.1746, 0.1577, 0.1341]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 16, acc 83.8
Network
tensor([[0.1144, 0.1484, 0.1587, 0.1772, 0.1080, 0.1317, 0.1617],
        [0.1242, 0.1378, 0.1722, 0.1172, 0.1862, 0.1341, 0.1283],
        [0.1884, 0.1430, 0.1528, 0.1096, 0.1167, 0.0955, 0.1939],
        [0.1184, 0.1094, 0.1306, 0.1966, 0.1739, 0.1083, 0.1628],
        [0.1744, 0.1585, 0.2053, 0.1278, 0.1342, 0.1146, 0.0852],
        [0.1714, 0.1298, 0.1706, 0.1577, 0.1217, 0.1430, 0.1059],
        [0.1781, 0.1260, 0.1690, 0.0998, 0.1143, 0.1689, 0.1439],
        [0.1375, 0.1298, 0.1845, 0.1686, 0.1211, 0.1003, 0.1583],
        [0.1790, 0.1442, 0.1393, 0.1295, 0.1503, 0.1259, 0.1319],
        [0.1706, 0.1103, 0.1261, 0.2103, 0.1205, 0.0967, 0.1656],
        [0.1632, 0.1306, 0.1389, 0.1495, 0.1047, 0.2040, 0.1091],
        [0.1988, 0.1336, 0.1238, 0.0900, 0.1380, 0.1964, 0.1195],
        [0.2189, 0.1358, 0.1340, 0.1132, 0.0966, 0.1439, 0.1576],
        [0.1717, 0.1181, 0.1422, 0.1059, 0.1791, 0.1513, 0.1317]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in 


epoch 17, acc 81.4
Network
tensor([[0.1126, 0.1434, 0.1569, 0.1850, 0.1072, 0.1330, 0.1619],
        [0.1222, 0.1331, 0.1724, 0.1145, 0.2004, 0.1313, 0.1263],
        [0.1989, 0.1409, 0.1502, 0.1085, 0.1111, 0.0896, 0.2008],
        [0.1173, 0.1037, 0.1280, 0.1985, 0.1806, 0.1045, 0.1673],
        [0.1774, 0.1642, 0.2177, 0.1238, 0.1281, 0.1094, 0.0794],
        [0.1791, 0.1293, 0.1754, 0.1571, 0.1180, 0.1395, 0.1017],
        [0.1841, 0.1241, 0.1748, 0.0947, 0.1086, 0.1694, 0.1443],
        [0.1361, 0.1302, 0.1936, 0.1683, 0.1177, 0.0930, 0.1612],
        [0.1824, 0.1416, 0.1372, 0.1304, 0.1536, 0.1278, 0.1271],
        [0.1743, 0.1054, 0.1244, 0.2176, 0.1211, 0.0908, 0.1665],
        [0.1654, 0.1277, 0.1381, 0.1514, 0.1001, 0.2133, 0.1039],
        [0.2043, 0.1303, 0.1201, 0.0848, 0.1318, 0.2092, 0.1195],
        [0.2350, 0.1359, 0.1343, 0.1067, 0.0937, 0.1441, 0.1504],
        [0.1798, 0.1153, 0.1441, 0.1015, 0.1786, 0.1498, 0.1310]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 18, acc 80.0
Network
tensor([[0.1105, 0.1415, 0.1553, 0.1912, 0.1040, 0.1356, 0.1620],
        [0.1193, 0.1304, 0.1723, 0.1125, 0.2160, 0.1278, 0.1217],
        [0.2101, 0.1395, 0.1478, 0.1070, 0.1058, 0.0848, 0.2052],
        [0.1114, 0.0995, 0.1255, 0.2068, 0.1863, 0.1015, 0.1689],
        [0.1817, 0.1681, 0.2292, 0.1182, 0.1229, 0.1050, 0.0749],
        [0.1857, 0.1290, 0.1801, 0.1551, 0.1142, 0.1377, 0.0982],
        [0.1897, 0.1225, 0.1783, 0.0902, 0.1039, 0.1721, 0.1434],
        [0.1332, 0.1300, 0.1987, 0.1672, 0.1184, 0.0877, 0.1649],
        [0.1893, 0.1387, 0.1346, 0.1275, 0.1573, 0.1298, 0.1230],
        [0.1778, 0.1001, 0.1211, 0.2303, 0.1209, 0.0856, 0.1643],
        [0.1658, 0.1243, 0.1351, 0.1535, 0.0970, 0.2242, 0.1001],
        [0.2150, 0.1274, 0.1166, 0.0813, 0.1248, 0.2207, 0.1142],
        [0.2481, 0.1347, 0.1325, 0.1013, 0.0920, 0.1442, 0.1471],
        [0.1895, 0.1127, 0.1444, 0.0982, 0.1769, 0.1479, 0.1305]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 19, acc 84.2
Network
tensor([[0.1067, 0.1382, 0.1510, 0.1994, 0.1016, 0.1392, 0.1639],
        [0.1184, 0.1279, 0.1693, 0.1112, 0.2254, 0.1272, 0.1206],
        [0.2199, 0.1387, 0.1439, 0.1037, 0.1020, 0.0791, 0.2126],
        [0.1060, 0.0940, 0.1227, 0.2115, 0.1971, 0.0981, 0.1707],
        [0.1864, 0.1670, 0.2356, 0.1147, 0.1242, 0.1015, 0.0706],
        [0.1895, 0.1270, 0.1814, 0.1620, 0.1084, 0.1351, 0.0965],
        [0.1996, 0.1220, 0.1809, 0.0850, 0.0996, 0.1694, 0.1434],
        [0.1369, 0.1262, 0.1995, 0.1671, 0.1160, 0.0840, 0.1703],
        [0.1936, 0.1372, 0.1326, 0.1218, 0.1640, 0.1317, 0.1190],
        [0.1788, 0.0980, 0.1205, 0.2407, 0.1197, 0.0809, 0.1614],
        [0.1610, 0.1190, 0.1331, 0.1550, 0.0980, 0.2373, 0.0965],
        [0.2256, 0.1316, 0.1171, 0.0756, 0.1200, 0.2182, 0.1119],
        [0.2647, 0.1357, 0.1335, 0.0938, 0.0895, 0.1420, 0.1408],
        [0.2015, 0.1077, 0.1417, 0.0944, 0.1799, 0.1483, 0.1265]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe



epoch 20, acc 80.4
Network
tensor([[0.1039, 0.1349, 0.1456, 0.2142, 0.0958, 0.1418, 0.1639],
        [0.1177, 0.1267, 0.1670, 0.1081, 0.2354, 0.1257, 0.1194],
        [0.2370, 0.1360, 0.1365, 0.1023, 0.0986, 0.0738, 0.2160],
        [0.1000, 0.0886, 0.1166, 0.2203, 0.2052, 0.0957, 0.1736],
        [0.1888, 0.1719, 0.2417, 0.1077, 0.1233, 0.1008, 0.0658],
        [0.1906, 0.1283, 0.1832, 0.1695, 0.1041, 0.1334, 0.0909],
        [0.2058, 0.1227, 0.1816, 0.0795, 0.0936, 0.1705, 0.1464],
        [0.1393, 0.1246, 0.2001, 0.1663, 0.1139, 0.0801, 0.1757],
        [0.1992, 0.1372, 0.1296, 0.1163, 0.1678, 0.1315, 0.1184],
        [0.1807, 0.0949, 0.1158, 0.2526, 0.1182, 0.0768, 0.1611],
        [0.1606, 0.1150, 0.1275, 0.1562, 0.0942, 0.2535, 0.0931],
        [0.2392, 0.1314, 0.1133, 0.0700, 0.1178, 0.2213, 0.1070],
        [0.2819, 0.1330, 0.1307, 0.0891, 0.0864, 0.1422, 0.1368],
        [0.2142, 0.1039, 0.1361, 0.0887, 0.1851, 0.1520, 0.1200]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe



epoch 21, acc 82.2
Network
tensor([[0.1030, 0.1338, 0.1440, 0.2238, 0.0903, 0.1439, 0.1612],
        [0.1152, 0.1255, 0.1662, 0.1075, 0.2450, 0.1241, 0.1165],
        [0.2451, 0.1321, 0.1331, 0.1023, 0.0962, 0.0706, 0.2206],
        [0.0952, 0.0854, 0.1152, 0.2261, 0.2062, 0.0948, 0.1770],
        [0.1858, 0.1725, 0.2530, 0.1064, 0.1225, 0.0987, 0.0612],
        [0.1920, 0.1269, 0.1865, 0.1759, 0.0998, 0.1325, 0.0864],
        [0.2095, 0.1202, 0.1849, 0.0742, 0.0868, 0.1741, 0.1501],
        [0.1424, 0.1225, 0.2044, 0.1641, 0.1113, 0.0762, 0.1792],
        [0.2086, 0.1382, 0.1265, 0.1138, 0.1641, 0.1337, 0.1151],
        [0.1822, 0.0922, 0.1117, 0.2675, 0.1180, 0.0738, 0.1546],
        [0.1614, 0.1123, 0.1246, 0.1510, 0.0936, 0.2656, 0.0915],
        [0.2545, 0.1332, 0.1118, 0.0651, 0.1161, 0.2162, 0.1030],
        [0.3004, 0.1333, 0.1298, 0.0845, 0.0807, 0.1391, 0.1323],
        [0.2299, 0.1032, 0.1359, 0.0844, 0.1783, 0.1515, 0.1168]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 22, acc 85.2
Network
tensor([[0.1027, 0.1297, 0.1420, 0.2320, 0.0871, 0.1451, 0.1614],
        [0.1167, 0.1224, 0.1638, 0.1045, 0.2557, 0.1227, 0.1142],
        [0.2585, 0.1279, 0.1264, 0.1030, 0.0936, 0.0667, 0.2238],
        [0.0918, 0.0808, 0.1123, 0.2294, 0.2109, 0.0957, 0.1791],
        [0.1809, 0.1697, 0.2643, 0.1073, 0.1219, 0.0976, 0.0582],
        [0.1919, 0.1274, 0.1944, 0.1814, 0.0925, 0.1293, 0.0831],
        [0.2129, 0.1191, 0.1911, 0.0683, 0.0821, 0.1747, 0.1519],
        [0.1429, 0.1210, 0.2119, 0.1621, 0.1083, 0.0711, 0.1828],
        [0.2142, 0.1410, 0.1289, 0.1117, 0.1615, 0.1330, 0.1097],
        [0.1831, 0.0910, 0.1097, 0.2786, 0.1184, 0.0703, 0.1490],
        [0.1609, 0.1115, 0.1228, 0.1447, 0.0932, 0.2792, 0.0877],
        [0.2650, 0.1342, 0.1127, 0.0614, 0.1123, 0.2140, 0.1004],
        [0.3203, 0.1324, 0.1278, 0.0806, 0.0744, 0.1339, 0.1305],
        [0.2459, 0.1030, 0.1383, 0.0802, 0.1708, 0.1507, 0.1112]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 23, acc 85.6
Network
tensor([[0.1014, 0.1264, 0.1410, 0.2419, 0.0831, 0.1462, 0.1599],
        [0.1151, 0.1208, 0.1664, 0.1023, 0.2666, 0.1193, 0.1095],
        [0.2633, 0.1262, 0.1248, 0.1033, 0.0908, 0.0625, 0.2291],
        [0.0883, 0.0781, 0.1118, 0.2357, 0.2160, 0.0935, 0.1766],
        [0.1772, 0.1711, 0.2778, 0.1049, 0.1208, 0.0939, 0.0544],
        [0.1920, 0.1293, 0.2074, 0.1828, 0.0858, 0.1233, 0.0794],
        [0.2132, 0.1180, 0.1979, 0.0645, 0.0809, 0.1771, 0.1483],
        [0.1439, 0.1187, 0.2166, 0.1579, 0.1043, 0.0669, 0.1918],
        [0.2268, 0.1476, 0.1341, 0.1042, 0.1532, 0.1319, 0.1023],
        [0.1861, 0.0907, 0.1077, 0.2889, 0.1142, 0.0674, 0.1450],
        [0.1639, 0.1111, 0.1197, 0.1384, 0.0903, 0.2935, 0.0831],
        [0.2809, 0.1349, 0.1119, 0.0572, 0.1089, 0.2096, 0.0966],
        [0.3493, 0.1301, 0.1238, 0.0759, 0.0685, 0.1270, 0.1254],
        [0.2664, 0.1047, 0.1415, 0.0739, 0.1593, 0.1483, 0.1058]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 24, acc 84.8
Network
tensor([[0.0986, 0.1229, 0.1377, 0.2530, 0.0812, 0.1455, 0.1610],
        [0.1145, 0.1208, 0.1717, 0.0999, 0.2680, 0.1190, 0.1060],
        [0.2690, 0.1239, 0.1225, 0.1049, 0.0874, 0.0587, 0.2335],
        [0.0855, 0.0761, 0.1141, 0.2357, 0.2185, 0.0909, 0.1793],
        [0.1739, 0.1764, 0.2909, 0.1006, 0.1174, 0.0899, 0.0510],
        [0.1935, 0.1284, 0.2156, 0.1869, 0.0800, 0.1193, 0.0761],
        [0.2211, 0.1188, 0.2047, 0.0595, 0.0785, 0.1698, 0.1477],
        [0.1463, 0.1153, 0.2173, 0.1591, 0.1007, 0.0618, 0.1994],
        [0.2343, 0.1528, 0.1371, 0.0985, 0.1492, 0.1320, 0.0961],
        [0.1895, 0.0908, 0.1061, 0.2957, 0.1121, 0.0636, 0.1423],
        [0.1706, 0.1142, 0.1194, 0.1322, 0.0894, 0.2960, 0.0784],
        [0.2969, 0.1343, 0.1099, 0.0533, 0.1036, 0.2102, 0.0918],
        [0.3755, 0.1273, 0.1191, 0.0707, 0.0642, 0.1206, 0.1226],
        [0.2895, 0.1063, 0.1431, 0.0683, 0.1512, 0.1438, 0.0977]],
       device='cuda:0', grad_fn=<SoftmaxBackwar

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, b


epoch 25, acc 83.6

accuracy  83.6, loss  0.5834117159247398
[(0, 2), (0, 3), (0, 4), (0, 5), (1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)]
['none', 'skip_connect', 'max_pool_3x3', 'sep_conv_3x3', 'sep_conv_5x5', 'dil_conv_3x3', 'dil_conv_5x5']
Files already downloaded and verified
Files already downloaded and verified



epoch 0, acc 51.4



epoch 1, acc 56.0



epoch 2, acc 63.2



epoch 3, acc 68.0



epoch 4, acc 70.6



epoch 5, acc 72.0



epoch 6, acc 73.6



epoch 7, acc 75.6



epoch 8, acc 77.4



epoch 9, acc 77.8



epoch 10, acc 79.2



epoch 11, acc 77.6



epoch 12, acc 82.2



epoch 13, acc 79.6



epoch 14, acc 79.2



epoch 15, acc 80.2



epoch 16, acc 81.0



epoch 17, acc 81.8



epoch 18, acc 82.0



epoch 19, acc 81.4



epoch 20, acc 82.0



epoch 21, acc 82.2



epoch 22, acc 82.2



epoch 23, acc 82.0



epoch 24, acc 83.2



epoch 25, acc 83.4



epoch 26, acc 83.2


Buffered data was truncated after reaching the output size limit.

In [ ]:
def _data_transforms_cifar10(args):
  CIFAR_MEAN = [0.49139968, 0.48215827, 0.44653124]
  CIFAR_STD = [0.24703233, 0.24348505, 0.26158768]

  train_transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(CIFAR_MEAN, CIFAR_STD),
  ])
  if args.cutout:
    train_transform.transforms.append(Cutout(args.cutout_length))

  valid_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(CIFAR_MEAN, CIFAR_STD),
    ])
  return train_transform, valid_transform

## viz

In [ ]:
# # cause a crash to increase RAM
# [_ for _ in range(10000000000)]

In [ ]:
# def main(description, **kwarg):

#   save_dir("")

#   use_cuda = torch.cuda.is_available()
#   device = torch.device("cuda" if use_cuda else "cpu")
#   print("device is %s" % device)

#   trainset, testset = load_dataset()
#   kwargs = {'num_workers': 1, 'pin_memory': True} if use_cuda else {}

#   class_array = [i for i in range(10)]

#   @dictspace
#   def learning(args):

#     store = Store(dir=args.dir)
#     store.add("kwargs", args)
#     theta_log = Store(dir=args.dir)

#     # instantiate
#     networkarg = {"depth" : args.depth, "node_num" : args.node,
#                   "input" : args.input, "multi" : args.multi}
#     model = CellNetwork(**networkarg)
#     model.to(device)

#     optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum, weight_decay=3e-4)
#     scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, float(args.epochs), eta_min=0.001)
#     optimizer_theta = optim.Adam(model.thetas, lr=args.lr_theta, betas=(0.5, 0.999), weight_decay=1e-3)
#     criterion = nn.CrossEntropyLoss()

#     trainset, testset = load_dataset(train=args.train_size)
#     trainloader = torch.utils.data.DataLoader(trainset, batch_size=args.batch_size, shuffle=False, **kwargs)
#     testloader = torch.utils.data.DataLoader(testset, batch_size=args.batch_size, shuffle=False, **kwargs)
    
#     # relearning
#     stop = EarlyStopping(patent=15)
#     accuracy, loss = 0, 1e10
#     remodel = CellNetwork(search=False, **networkarg).to(device)
#     remodel.thetas = [torch.tensor([
#         [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
#         [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
#        device='cuda:0'), torch.tensor([
#         [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
#        device='cuda:0')]
#     remodel.sampling()
#     model = remodel
#     model.plot(os.path.join(args.dir, "complete_"))

#     optimizer = optim.SGD(model.parameters(), lr=args.relr, momentum=args.momentum, weight_decay=3e-4)
#     scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, float(args.epochs), eta_min=0.001)
#     for epoch in range(args.epochs):
      
#       (_, loss_train) = train(model, device, trainloader, optimizer, None, criterion, None, class_array)
#       (_, (loss_test, acc)) = test(model, device, testloader, criterion, None, class_array)
#       scheduler.step()

#       print('epoch %d, acc %s' % (epoch, acc))
#       store.add("loss", loss_test)
#       store.add("acc", acc)

#       accuracy, loss = acc, loss_test
#       stop.step(loss_test)
#       # if stop.is_stop():
#         # break

#     print("\naccuracy ", accuracy, end=", ")
#     print("loss ", loss)
#     SaveModel("cell", model, dir=args.dir)
#     print(store)
#     store.save()
#     theta_log.save(name="theta")
#     store.save_fig()
#     if args.save_dir: save_dir(args.dir)

#     del model

#     return loss

#   kwarg['dir'] = get_time()
#   if not os.path.exists(kwarg['dir']):
#     os.mkdir(kwarg['dir'])
#   learning(**kwarg)